config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get "about", to: 'pages#about'
  resources :articles
  resources :songs#, only: [ :show, :index, :new, :create, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum:6, maximum:10}
    validates :description, presence: true, length: {minimum:10, maximum:310}
end

app/models/song.rb
class Song < ApplicationRecord 
    validates :title, presence: true, length: {minimum:6, maximum:10}
    validates :description, presence: true, length: {minimum:10, maximum:310}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        render html: 'hello world'
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def show
        @song = Song.find(params[:id])
    end

    def index
        @songs = Song.all
    end

    def new
        @song = Song.new
    end

    def edit
        @song = Song.find(params[:id])
    end
    

    def create
        @song = Song.new(params.require(:song).permit(:title, :description))
        if @song.save
          flash[:notice] = "Song was created successfully"
          redirect_to @song 
        else
          render 'new'
        end
    end

    def update
        @song = Song.find(params[:id])
        if @song.update(params.require(:song).permit(:title, :description))
            flash[:notice] = "Song was updated successfully"
            redirect_to @song 
        else
            render 'edit'
        end 
    end

    def destroy
        @song = Song.find(params[:id])
        @song.destroy
        redirect_to songs_path
    end
    
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg|%>
      <%= msg %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/home.html.erb
Hello world
<h1>This is a home page</h1>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<% if @song.errors.any? %> 
  <h2>The following errors prevented the article from being saved</h2> 
  <ul> 
    <% @song.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
    <% end %> 
  </ul>
<% end %>


<%= form_with(model: @song, local: true)  do |f|  %>
<p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
</p>

<p>
    <%= f.submit %>
</p>
<% end %>

app/views/songs/index.html.erb
<h1> Songs</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @songs.each do |song| %>
        <tr>
            <td><%= song.title%></td>
            <td><%= song.description%></td>
            <td><%= link_to "Show", song_path(song) %></td>
            <td><%= link_to "Edit", song_path(song) %></td>
            <td><%= link_to "Delete", song_path(song), method: :delete %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/songs/new.html.erb
<h1>Create Song</h1>

<% if @song.errors.any? %> 
  <h2>The following errors prevented the article from being saved</h2> 
  <ul> 
    <% @song.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
    <% end %> 
  </ul>
<% end %>


<%= form_with scope: :song, url: songs_path, local: true do |f|  %>
<p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
</p>

<p>
    <%= f.submit %>
</p>
<% end %>

app/views/songs/show.html.erb
<h1> Song details</h1>
<p><strong>Title: <%=  @song.title %></strong></p>
<p><strong>Title: <%= @song.description%></strong></p>